In [2]:
import numpy as np

In [3]:
myarr=np.array([[1,2,3,4]],np.int8)

In [4]:
myarr

array([[1, 2, 3, 4]], dtype=int8)

In [5]:
myarr[0,1]

np.int8(2)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int8')

In [8]:
myarr[0,1]=23
myarr

array([[ 1, 23,  3,  4]], dtype=int8)

# Array creation : Conversion from other python structures to array

In [9]:
list_array=np.array([[1,2,3,4,5],[2,3,4,4,3]])

In [10]:
list_array

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 4, 3]])

In [11]:
list_array.dtype

dtype('int64')

In [12]:
list_array.shape

(2, 5)

In [13]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [14]:
zeros=np.zeros((2,5))

In [15]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace=np.linspace(1,5,12) # 12 equally distant numbers from 1 to 5 

In [18]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [19]:
emp=np.empty((4,6)) # empty array with shape 4 X 6 filled with random elements

In [20]:
emp


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.45599366e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        1.69118108e-306, 7.56599128e-307, 1.42410974e-306]])

In [21]:
emp_like=np.empty_like(lspace)

In [22]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
ide=np.identity(45*45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(2025, 2025))

In [25]:
ide.shape

(2025, 2025)

In [26]:
arr= np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
# reshape the give shape
arr1=arr.reshape(3,33) #3 * 33=99
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [51]:
arr=arr.ravel()

In [53]:
print(arr.shape)

(99,)


In [48]:
x=[[1,2,3],[4,5,6],[7,1,0]]


In [54]:
ar=np.array(x)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.sum(axis=0) #sum of elements of rows

array([12,  8,  9])

In [59]:
ar.sum(axis=1) #sum of elements of colulmn

array([ 6, 15,  8])

In [60]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [63]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [64]:
ar.ndim

2

In [65]:
ar.size

9

In [66]:
ar.nbytes

72

In [72]:
one=np.array([1,2,3,4])


In [73]:
one.argmax()

np.int64(3)

In [74]:
one.argmin()

np.int64(0)

In [76]:
one.argsort() #gives index in sorted order

array([0, 1, 2, 3])

In [77]:
ar.argmax()

np.int64(6)

In [78]:
ar.argmax(axis=1)

array([2, 2, 0])

In [81]:
ar2=np.array([[1,2,23],[1,2,3],[4,5,6]])

In [82]:
ar+ar2


array([[ 2,  4, 26],
       [ 5,  7,  9],
       [11,  6,  6]])

In [83]:
ar*ar2

array([[ 1,  4, 69],
       [ 4, 10, 18],
       [28,  5,  0]])

In [84]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [86]:
ar.sum()

np.int64(29)

In [87]:
ar.max()

np.int64(7)

In [88]:
ar.min()

np.int64(0)

In [89]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [92]:
np.count_nonzero(ar)

np.int64(8)

In [94]:
np.nonzero(ar) #gives the tuple of index of non zero elements


(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [95]:
import sys

In [96]:
ch_ar=[0,4,2,11]

In [104]:
np_arr=np.array(ch_ar)

In [105]:
sys.getsizeof(1) * len(ch_ar)

112

In [106]:
np_arr.itemsize * np_arr.size

32